# Generated by Django 5.0.3 on 2024-03-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_alter_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='eventName',
        ),
    ]
